name: branding

on:
  workflow_dispatch:
    inputs:
      slug:
        description: Replicated App Slug
        required: true
        type: string
      api-token:
        description: Replicated API Token
        required: false
        type: string
      api-origin:
        description: Replicated API Origin
        required: false
        default: https://api.replicated.com/vendor
        type: string

jobs:
  prepare:
    runs-on: ubuntu-22.04
    outputs:
      api-token: ${{ steps.prepare.outputs.api-token }}
      api-origin: ${{ steps.prepare.outputs.api-origin }}
      app-id: ${{ steps.app-id.outputs.app-id }}
    steps:
      - name: Prepare for Vendor API connection
        id: prepare
        run: |
          # Use provided token or fall back to secret
          if [ -n "${{ inputs.api-token }}" ]; then
            echo "api-token=${{ inputs.api-token }}" >> $GITHUB_OUTPUT
          else
            echo "api-token=${{ secrets.REPLICATED_API_TOKEN }}" >> $GITHUB_OUTPUT
          fi
          
          # Use provided origin or fall back to default
          echo "api-origin=${{ inputs.api-origin }}" >> $GITHUB_OUTPUT

      - name: Install Replicated CLI
        run: |
          curl -sSL https://raw.githubusercontent.com/replicatedhq/replicated/master/install.sh \
            | sudo bash

      - name: Fetch the application ID from the slug
        id: app-id
        run: |
          app_id=$(replicated app ls --output json | jq -r --arg slug "${{ inputs.slug }}" '.[] | select ( .app.slug == $slug ) | .app.id')
          echo "app-id=${app_id}" >> $GITHUB_OUTPUT

  portal:
    runs-on: ubuntu-22.04
    needs: 
      - prepare
    steps:
      - name: Install Replicated CLI
        run: |
          curl -sSL https://raw.githubusercontent.com/replicatedhq/replicated/master/install.sh | 
            sudo bash
      
      - name Checkout branding
        uses: actions/checkout@v4

      - name: Setup the Enterprise Portal branding
        run: |
          replicated api put /v3/app/${APP_ID}/enterpriseportal/branding \
            --body "$(cat branding/branding.json)"
        env:
          APP_ID: ${{ needs.prepare.outputs.app-id }}
          REPLICATED_API_TOKEN: ${{ needs.prepare.outputs.api-token }}
          REPLICATED_API_ORIGIN: ${{ needs.prepare.outputs.api-origin }}


  email:
    runs-on: ubuntu-22.04
    needs: 
      - prepare
    steps:
      - name: Install Replicated CLI
        run: |
          curl -sSL https://raw.githubusercontent.com/replicatedhq/replicated/master/install.sh | 
            sudo bash

      - name Checkout branding
        uses: actions/checkout@v4

      - name: Setup the Enterprise Portal email templates
        run: |
          replicated api put /v3/app/${APP_ID}/enterpriseportal/email-templates \
            --body "$(cat branding/email-templates.json)"
        env:
          APP_ID: ${{ needs.prepare.outputs.app-id }}
          REPLICATED_API_TOKEN: ${{ needs.prepare.outputs.api-token }}
          REPLICATED_API_ORIGIN: ${{ needs.prepare.outputs.api-origin }}
